# Generated by Django 4.1.5 on 2024-10-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntier',
            name='experiences',
            field=models.CharField(default='', max_length=100, verbose_name='Experiences'),
        ),
        migrations.AddField(
            model_name='voluntier',
            name='languages',
            field=models.CharField(default='', max_length=100, verbose_name='Languages'),
        ),
    ]
