# Generated by Django 4.1.5 on 2024-11-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntier',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='voluntier',
            name='languages',
        ),
        migrations.AddField(
            model_name='voluntier',
            name='about',
            field=models.CharField(default='', max_length=100, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='voluntier',
            name='linkedin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
