# Generated by Django 5.1.1 on 2024-11-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntier',
            name='about',
            field=models.TextField(default='', max_length=5000, verbose_name='About'),
        ),
    ]
