# Generated by Django 5.1.1 on 2024-11-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_voluntier_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntier',
            name='about',
            field=models.CharField(default='', max_length=100, verbose_name='About'),
        ),
    ]
