# Generated by Django 5.1.1 on 2024-11-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_voluntier_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntier',
            name='about',
            field=models.TextField(default='', max_length=2500, verbose_name='About'),
        ),
    ]
