# Generated by Django 4.1.5 on 2024-10-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='institution',
            name='logradouro',
            field=models.CharField(default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='State'),
        ),
    ]
