# Generated by Django 5.1.1 on 2024-11-14 14:09

import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_voluntier_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[profiles.validators.validate_cnpj]),
        ),
        migrations.AlterField(
            model_name='voluntier',
            name='about',
            field=models.CharField(default='', max_length=100, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='voluntier',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[profiles.validators.validate_cpf]),
        ),
    ]
