# Generated by Django 4.0 on 2024-06-25 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='positions.category')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='Title')),
                ('description', models.CharField(max_length=165, verbose_name='Description')),
                ('slug', models.SlugField(unique=True)),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('requirements_is_html', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('cover', models.ImageField(blank=True, default='', upload_to='positions/covers/%Y/%m/%d/', verbose_name='Cover')),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], default='morning', max_length=10, verbose_name='Shift')),
                ('state', models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro')], max_length=100, verbose_name='State')),
                ('city', models.CharField(choices=[('São Paulo', 'São Paulo'), ('Rio de Janeiro', 'Rio de Janeiro')], max_length=100, verbose_name='City')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Address')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.institution')),
                ('subcategory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cvs/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_vaga', to='positions.position', verbose_name='position')),
                ('voluntier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.voluntier')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
            },
        ),
    ]
