# Generated by Django 4.1.5 on 2024-11-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.institution'),
        ),
        migrations.AddField(
            model_name='position',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.subcategory', verbose_name='Subcategory'),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_vaga', to='positions.position', verbose_name='position'),
        ),
        migrations.AddField(
            model_name='application',
            name='voluntier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.voluntier'),
        ),
    ]
