# Generated by Django 5.1.1 on 2024-11-12 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='voluntier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.voluntier'),
        ),
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='position',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.institution'),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_vaga', to='positions.position', verbose_name='position'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='positions.category'),
        ),
        migrations.AddField(
            model_name='position',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.subcategory', verbose_name='Subcategory'),
        ),
    ]
