# Generated by Django 4.1.5 on 2024-10-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_alter_vacancy_category_alter_vacancy_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='zone',
            field=models.CharField(choices=[('Central', 'Central'), ('Leste', 'Leste'), ('Oeste', 'Oeste'), ('Norte', 'Norte'), ('Sul', 'Sul')], default='', max_length=100, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='position',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil')], max_length=100, verbose_name='Country'),
        ),
    ]
