# Generated by Django 4.1.5 on 2024-10-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_remove_position_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='country',
        ),
    ]
