# Generated by Django 5.0.6 on 2024-06-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(choices=[('São Paulo', 'São Paulo'), ('Rio de Janeiro', 'Rio de Janeiro')], max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil'), ('US', 'United States')], max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='state',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro')], max_length=100, verbose_name='State'),
        ),
    ]
